### ISSUE TITLE
Implement events section

### ISSUE THREAD

**Issue by shanewalters** [shanewalters/jams#40]
Under the "about" page, there is an event section. This is a list of calendar events, which will come from the Event table. Tasks required to complete this issue are:

- [x] Change SectionTypeId to match the event section type (see SectionType table) for the single event section currently in the DB.
- [x] Move example event data from Section.Content to individual Event records.
- [x] Replace current Content (HTML) with an empty string.
- [x] Add data logic method to query event data.
- [x] Update About model to have a new property to hold event data.
- [x] Update Index() action, on About.cs controller, to initialize event data in model.
- [x] Inside existing foreach loop (in About.cshtml), add a conditional check for section type names. If section type name = "Event" then, use the model event data.
- [x] The event data HTML and CSS will all be setup in About.cshtml, and will not come from the DB.

**Comment by lilipenggg** [comment]
Done since pull request #44 is merged
